import Navbar from "@/components/Navbar.js"
import "./globals.css"

import {
	ClerkProvider,
	SignInButton,
	SignUpButton,
	SignedIn,
	SignedOut,
	UserButton,
} from "@clerk/nextjs";

export const metadata = {
	title: "Waste2Plate",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className="antialiased">
					<header className="flex justify-end items-center p-4 gap-4 h-16">
						<SignedOut>
							<SignInButton />
							<SignUpButton />
						</SignedOut>
						<SignedIn>
							<UserButton />
						</SignedIn>
					</header>
					<Navbar />
					{children}
					<Footer />
				</body>
			</html>
		</ClerkProvider>
	);
}
